project:
  type: website

website:
  title: "Semagrams"
  navbar:
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - docs.qmd
      - href: /scaladoc/
        text: API

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    highlight: false
