project:
  type: website

website:
  title: "Semagrams"
  navbar:
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - roadmap.qmd
      - href: /scaladoc/
        text: Scaladoc

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



