pages = [{"l":"index.html#","e":false,"i":"","n":"semagrams","t":"semagrams","d":"","k":"static","x":""},
{"l":"semagrams.html#","e":false,"i":"","n":"semagrams","t":"semagrams","d":"","k":"package","x":""},
{"l":"semagrams/bindings.html#","e":false,"i":"","n":"semagrams.bindings","t":"semagrams.bindings","d":"","k":"package","x":""},
{"l":"semagrams/bindings/Action.html#","e":false,"i":"","n":"Action","t":"Action extends Described","d":"semagrams.bindings","k":"trait","x":""},
{"l":"semagrams/bindings/Action.html#apply-f6f","e":false,"i":"","n":"apply","t":"apply(res: Resources): IO[Option[Balloon[LocalEvent, Patch]]]","d":"semagrams.bindings.Action","k":"def","x":""},
{"l":"semagrams/bindings/Action$.html#","e":false,"i":"","n":"Action","t":"Action","d":"semagrams.bindings","k":"object","x":""},
{"l":"semagrams/bindings/Action$$Resources.html#","e":false,"i":"","n":"Resources","t":"Resources(instanceTether: Tether[Patch, Clean], globalTether: Tether[GlobalEvent, GlobalState], editorTether: Tether[Event, EditorState])","d":"semagrams.bindings.Action","k":"class","x":""},
{"l":"semagrams/bindings/AddAtMouse.html#","e":false,"i":"","n":"AddAtMouse","t":"AddAtMouse(sort: SortId) extends PureAction","d":"semagrams.bindings","k":"class","x":""},
{"l":"semagrams/bindings/AddAtMouse.html#description-0","e":false,"i":"","n":"description","t":"description: String","d":"semagrams.bindings.AddAtMouse","k":"val","x":""},
{"l":"semagrams/bindings/AddAtMouse.html#mutateState-450","e":false,"i":"","n":"mutateState","t":"mutateState(editorState: EditorState, state: Dirty): Unit","d":"semagrams.bindings.AddAtMouse","k":"def","x":""},
{"l":"semagrams/bindings/Binding.html#","e":false,"i":"","n":"Binding","t":"Binding[Model]","d":"semagrams.bindings","k":"trait","x":""},
{"l":"semagrams/bindings/Binding.html#EventData-0","e":false,"i":"","n":"EventData","t":"EventData","d":"semagrams.bindings.Binding","k":"type","x":""},
{"l":"semagrams/bindings/Binding.html#action-0","e":false,"i":"","n":"action","t":"action: Action","d":"semagrams.bindings.Binding","k":"val","x":""},
{"l":"semagrams/bindings/Binding.html#hook-0","e":false,"i":"","n":"hook","t":"hook: EventHook[EventData]","d":"semagrams.bindings.Binding","k":"val","x":""},
{"l":"semagrams/bindings/ClickOnPartHook.html#","e":false,"i":"","n":"ClickOnPartHook","t":"ClickOnPartHook(button: MouseButton, modifiers: Set[KeyModifier]) extends EventHook[Part]","d":"semagrams.bindings","k":"class","x":""},
{"l":"semagrams/bindings/ClickOnPartHook.html#apply-e6c","e":false,"i":"","n":"apply","t":"apply(evt: LocalEvent, globalState: GlobalState): Option[Part]","d":"semagrams.bindings.ClickOnPartHook","k":"def","x":""},
{"l":"semagrams/bindings/ClickOnPartHook.html#description-0","e":false,"i":"","n":"description","t":"description: String","d":"semagrams.bindings.ClickOnPartHook","k":"def","x":""},
{"l":"semagrams/bindings/ClickOnPartHook$.html#","e":false,"i":"","n":"ClickOnPartHook","t":"ClickOnPartHook","d":"semagrams.bindings","k":"object","x":""},
{"l":"semagrams/bindings/ClickOnPartHook$.html#apply-434","e":false,"i":"","n":"apply","t":"apply(button: MouseButton): ClickOnPartHook","d":"semagrams.bindings.ClickOnPartHook","k":"def","x":""},
{"l":"semagrams/bindings/EventHook.html#","e":false,"i":"","n":"EventHook","t":"EventHook[A]","d":"semagrams.bindings","k":"trait","x":""},
{"l":"semagrams/bindings/EventHook.html#apply-e6c","e":false,"i":"","n":"apply","t":"apply(evt: LocalEvent, globalState: GlobalState): Option[A]","d":"semagrams.bindings.EventHook","k":"def","x":""},
{"l":"semagrams/bindings/EventHook.html#description-0","e":false,"i":"","n":"description","t":"description: String","d":"semagrams.bindings.EventHook","k":"def","x":""},
{"l":"semagrams/bindings/KeyDownHook.html#","e":false,"i":"","n":"KeyDownHook","t":"KeyDownHook(key: String) extends EventHook[Unit]","d":"semagrams.bindings","k":"class","x":""},
{"l":"semagrams/bindings/KeyDownHook.html#apply-e6c","e":false,"i":"","n":"apply","t":"apply(evt: LocalEvent, _globalState: GlobalState): Option[Unit]","d":"semagrams.bindings.KeyDownHook","k":"def","x":""},
{"l":"semagrams/bindings/KeyDownHook.html#description-0","e":false,"i":"","n":"description","t":"description: String","d":"semagrams.bindings.KeyDownHook","k":"def","x":""},
{"l":"semagrams/bindings/PureAction.html#","e":false,"i":"","n":"PureAction","t":"PureAction extends Described","d":"semagrams.bindings","k":"trait","x":""},
{"l":"semagrams/bindings/PureAction.html#makePatch-fffffb49","e":false,"i":"","n":"makePatch","t":"makePatch(editorState: EditorState, clean: Clean): Patch","d":"semagrams.bindings.PureAction","k":"def","x":""},
{"l":"semagrams/bindings/PureAction.html#mutateState-450","e":false,"i":"","n":"mutateState","t":"mutateState(editorState: EditorState, state: Dirty): Unit","d":"semagrams.bindings.PureAction","k":"def","x":""},
{"l":"semagrams/util.html#","e":false,"i":"","n":"semagrams.util","t":"semagrams.util","d":"","k":"package","x":""},
{"l":"semagrams/util.html#*-b83","e":false,"i":"extension (t: Double)","n":"*","t":"*(z: Complex): Complex","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#^-44b","e":false,"i":"extension (t: Double)","n":"^","t":"^(x: Double): Double","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#bijectiveRW-fffff0c5","e":false,"i":"","n":"bijectiveRW","t":"bijectiveRW[A](as: Iterable[A]): ReadWriter[A]","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#boxSize-fffff113","e":false,"i":"","n":"boxSize","t":"boxSize(text: String, fontSize: Double): Complex","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#fromMaybe-456","e":false,"i":"","n":"fromMaybe","t":"fromMaybe[Model, A](a: IO[Option[A]]): IO[A]","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#msgError-fffff2d0","e":false,"i":"","n":"msgError","t":"msgError(msg: String): RuntimeException","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#onCancelOrError-fffffc67","e":false,"i":"extension [A](action: IO[A])","n":"onCancelOrError","t":"onCancelOrError(fin: IO[A]): IO[A]","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#splitTuple-9f4","e":false,"i":"extension [A, B](s: Signal[(A, B)])","n":"splitTuple","t":"splitTuple: (Signal[A], Signal[B])","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#toOption-fd5","e":false,"i":"extension [A](action: IO[A])","n":"toOption","t":"toOption: IO[Option[A]]","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#toSvg-a90","e":false,"i":"extension (elts: Seq[Element])","n":"toSvg","t":"toSvg: String","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#unwrap-69a","e":false,"i":"extension [A](x: Option[A])","n":"unwrap","t":"unwrap[F[_]](implicit F: MonadError[F, Throwable]): F[A]","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util.html#wrappedHtml-fffffd94","e":false,"i":"","n":"wrappedHtml","t":"wrappedHtml(el: Element, pos: Signal[Complex], dims: Signal[Complex]): ReactiveSvgElement[SVGElement]","d":"semagrams.util","k":"def","x":""},
{"l":"semagrams/util/CustomAttr$.html#","e":false,"i":"","n":"CustomAttr","t":"CustomAttr","d":"semagrams.util","k":"object","x":""},
{"l":"semagrams/util/CustomAttr$$CustomSvgAttr.html#","e":false,"i":"","n":"CustomSvgAttr","t":"CustomSvgAttr[Data]","d":"semagrams.util.CustomAttr","k":"trait","x":""},
{"l":"semagrams/util/CustomAttr$$CustomSvgAttr.html#:=-63b","e":false,"i":"","n":":=","t":":=(v: Data): Modifier[SvgElement]","d":"semagrams.util.CustomAttr.CustomSvgAttr","k":"def","x":""},
{"l":"semagrams/util/CustomAttr$$CustomSvgAttr.html#<---fffff04f","e":false,"i":"","n":"<--","t":"<--($value: Source[Data]): Modifier[SvgElement]","d":"semagrams.util.CustomAttr.CustomSvgAttr","k":"def","x":""},
{"l":"semagrams/util/CustomAttr$$CustomSvgAttr.html#applyAttrs-3da","e":false,"i":"","n":"applyAttrs","t":"applyAttrs(binder: SvgBinder[Data]): Unit","d":"semagrams.util.CustomAttr.CustomSvgAttr","k":"def","x":""},
{"l":"semagrams/util/CustomAttr$$ReactiveSvgBinder.html#","e":false,"i":"","n":"ReactiveSvgBinder","t":"ReactiveSvgBinder[Data](el: SvgElement, $x: Source[Data]) extends SvgBinder[Data]","d":"semagrams.util.CustomAttr","k":"class","x":""},
{"l":"semagrams/util/CustomAttr$$ReactiveSvgBinder.html#apply-4f2","e":false,"i":"","n":"apply","t":"apply[Subpart](attr: SvgAttr[Subpart], f: Data => Subpart): Unit","d":"semagrams.util.CustomAttr.ReactiveSvgBinder","k":"def","x":""},
{"l":"semagrams/util/CustomAttr$$StaticSvgBinder.html#","e":false,"i":"","n":"StaticSvgBinder","t":"StaticSvgBinder[Data](el: SvgElement, x: Data) extends SvgBinder[Data]","d":"semagrams.util.CustomAttr","k":"class","x":""},
{"l":"semagrams/util/CustomAttr$$StaticSvgBinder.html#apply-4f2","e":false,"i":"","n":"apply","t":"apply[Subpart](attr: SvgAttr[Subpart], f: Data => Subpart): Unit","d":"semagrams.util.CustomAttr.StaticSvgBinder","k":"def","x":""},
{"l":"semagrams/util/CustomAttr$$SvgBinder.html#","e":false,"i":"","n":"SvgBinder","t":"SvgBinder[Data]","d":"semagrams.util.CustomAttr","k":"trait","x":""},
{"l":"semagrams/util/CustomAttr$$SvgBinder.html#apply-4f2","e":false,"i":"","n":"apply","t":"apply[Subpart](attr: SvgAttr[Subpart], f: Data => Subpart): Unit","d":"semagrams.util.CustomAttr.SvgBinder","k":"def","x":""},
{"l":"semagrams/util/Described.html#","e":false,"i":"","n":"Described","t":"Described","d":"semagrams.util","k":"trait","x":""},
{"l":"semagrams/util/Described.html#description-0","e":false,"i":"","n":"description","t":"description: String","d":"semagrams.util.Described","k":"val","x":""},
{"l":"semagrams/util/LensedVar.html#","e":false,"i":"","n":"LensedVar","t":"LensedVar[A, B](val v: UndoableVar[A], val l: Lens[A, B])","d":"semagrams.util","k":"class","x":""},
{"l":"semagrams/util/LensedVar.html#l-0","e":false,"i":"","n":"l","t":"l: Lens[A, B]","d":"semagrams.util.LensedVar","k":"val","x":""},
{"l":"semagrams/util/LensedVar.html#signal-0","e":false,"i":"","n":"signal","t":"signal: Signal[B]","d":"semagrams.util.LensedVar","k":"val","x":""},
{"l":"semagrams/util/LensedVar.html#v-0","e":false,"i":"","n":"v","t":"v: UndoableVar[A]","d":"semagrams.util.LensedVar","k":"val","x":""},
{"l":"semagrams/util/LensedVar.html#writer-0","e":false,"i":"","n":"writer","t":"writer: Observer[B]","d":"semagrams.util.LensedVar","k":"val","x":""},
{"l":"semagrams/util/LensedVar.html#zoomL-a5e","e":false,"i":"","n":"zoomL","t":"zoomL[C](m: Lens[B, C]): LensedVar[A, C]","d":"semagrams.util.LensedVar","k":"def","x":""},
{"l":"semagrams/util/NoneError$.html#","e":false,"i":"","n":"NoneError","t":"NoneError extends Exception","d":"semagrams.util","k":"object","x":""},
{"l":"semagrams/util/Path$.html#","e":false,"i":"","n":"Path","t":"Path","d":"semagrams.util","k":"object","x":""},
{"l":"semagrams/util/Path$$Element.html#","e":false,"i":"","n":"Element","t":"Element","d":"semagrams.util.Path","k":"enum","x":""},
{"l":"semagrams/util/Path$$Element$$MoveTo.html#","e":false,"i":"","n":"MoveTo","t":"MoveTo(p: Complex)","d":"semagrams.util.Path.Element","k":"case","x":""},
{"l":"semagrams/util/Path$$Element$$LineTo.html#","e":false,"i":"","n":"LineTo","t":"LineTo(p: Complex)","d":"semagrams.util.Path.Element","k":"case","x":""},
{"l":"semagrams/util/Path$$Element$$Cubic.html#","e":false,"i":"","n":"Cubic","t":"Cubic(cs: Complex, ce: Complex, p: Complex)","d":"semagrams.util.Path.Element","k":"case","x":""},
{"l":"semagrams/util/Path$$Element.html#ClosePath-0","e":false,"i":"","n":"ClosePath","t":"ClosePath extends Element","d":"semagrams.util.Path.Element","k":"case","x":""},
{"l":"semagrams/util/Path$$Element$$MoveTo.html#","e":false,"i":"","n":"MoveTo","t":"MoveTo(p: Complex)","d":"semagrams.util.Path.Element","k":"case","x":""},
{"l":"semagrams/util/Path$$Element$$LineTo.html#","e":false,"i":"","n":"LineTo","t":"LineTo(p: Complex)","d":"semagrams.util.Path.Element","k":"case","x":""},
{"l":"semagrams/util/Path$$Element$$Cubic.html#","e":false,"i":"","n":"Cubic","t":"Cubic(cs: Complex, ce: Complex, p: Complex)","d":"semagrams.util.Path.Element","k":"case","x":""},
{"l":"semagrams/util/Transform.html#","e":false,"i":"","n":"Transform","t":"Transform(z: Complex, w: Complex)","d":"semagrams.util","k":"class","x":""},
{"l":"semagrams/util/Transform.html#apply-16a","e":false,"i":"","n":"apply","t":"apply(p: Complex): Complex","d":"semagrams.util.Transform","k":"def","x":""},
{"l":"semagrams/util/Transform.html#inverse-16a","e":false,"i":"","n":"inverse","t":"inverse(p: Complex): Complex","d":"semagrams.util.Transform","k":"def","x":""},
{"l":"semagrams/util/Transform.html#shift-a0d","e":false,"i":"","n":"shift","t":"shift(by: Complex): Transform","d":"semagrams.util.Transform","k":"def","x":""},
{"l":"semagrams/util/Transform.html#toSvg-0","e":false,"i":"","n":"toSvg","t":"toSvg: String","d":"semagrams.util.Transform","k":"def","x":""},
{"l":"semagrams/util/Transform.html#zoomAtPos-8e6","e":false,"i":"","n":"zoomAtPos","t":"zoomAtPos(factor: Double, pos: Complex): Transform","d":"semagrams.util.Transform","k":"def","x":""},
{"l":"semagrams/util/Transform.html#zoomBy-291","e":false,"i":"","n":"zoomBy","t":"zoomBy(factor: Double): Transform","d":"semagrams.util.Transform","k":"def","x":""},
{"l":"semagrams/util/Transform$.html#","e":false,"i":"","n":"Transform","t":"Transform","d":"semagrams.util","k":"object","x":""},
{"l":"semagrams/util/Transform$.html#identity-0","e":false,"i":"","n":"identity","t":"identity: Transform","d":"semagrams.util.Transform","k":"val","x":""},
{"l":"semagrams/util/UndoState.html#","e":false,"i":"","n":"UndoState","t":"UndoState[A](recording: Boolean, past: List[A], present: A, future: List[A])","d":"semagrams.util","k":"class","x":""},
{"l":"semagrams/util/UndoState.html#redo-299","e":false,"i":"","n":"redo","t":"redo(): UndoState[A]","d":"semagrams.util.UndoState","k":"def","x":""},
{"l":"semagrams/util/UndoState.html#save-299","e":false,"i":"","n":"save","t":"save(): UndoState[A]","d":"semagrams.util.UndoState","k":"def","x":""},
{"l":"semagrams/util/UndoState.html#undo-299","e":false,"i":"","n":"undo","t":"undo(): UndoState[A]","d":"semagrams.util.UndoState","k":"def","x":""},
{"l":"semagrams/util/UndoState.html#update-fffff32c","e":false,"i":"","n":"update","t":"update(a: A): UndoState[A]","d":"semagrams.util.UndoState","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#","e":false,"i":"","n":"UndoableVar","t":"UndoableVar[A](init: A) extends SignalSource[A], Sink[A]","d":"semagrams.util","k":"class","x":""},
{"l":"semagrams/util/UndoableVar.html#now-993","e":false,"i":"","n":"now","t":"now(): A","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#record-94c","e":false,"i":"","n":"record","t":"record(): Unit","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#redo-94c","e":false,"i":"","n":"redo","t":"redo(): Unit","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#save-94c","e":false,"i":"","n":"save","t":"save(): Unit","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#set-fffff71f","e":false,"i":"","n":"set","t":"set(a: A): Unit","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#signal-0","e":false,"i":"","n":"signal","t":"signal: Signal[A]","d":"semagrams.util.UndoableVar","k":"val","x":""},
{"l":"semagrams/util/UndoableVar.html#toObservable-0","e":false,"i":"","n":"toObservable","t":"toObservable: Signal[A]","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#toObserver-0","e":false,"i":"","n":"toObserver","t":"toObserver: Observer[A]","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#undo-94c","e":false,"i":"","n":"undo","t":"undo(): Unit","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#unrecord-94c","e":false,"i":"","n":"unrecord","t":"unrecord(): Unit","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#update-c9d","e":false,"i":"","n":"update","t":"update(f: A => A): Unit","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#updateS-fffff302","e":false,"i":"","n":"updateS","t":"updateS[B](s: State[A, B]): IO[B]","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#updateS_-fffff302","e":false,"i":"","n":"updateS_","t":"updateS_[B](s: State[A, B]): IO[Unit]","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#updater-fffff541","e":false,"i":"","n":"updater","t":"updater[B](f: (A, B) => A): Observer[B]","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/UndoableVar.html#writer-0","e":false,"i":"","n":"writer","t":"writer: Observer[A]","d":"semagrams.util.UndoableVar","k":"val","x":""},
{"l":"semagrams/util/UndoableVar.html#zoomL-a5e","e":false,"i":"","n":"zoomL","t":"zoomL[B](l: Lens[A, B]): LensedVar[A, B]","d":"semagrams.util.UndoableVar","k":"def","x":""},
{"l":"semagrams/util/complexattrs$.html#","e":false,"i":"","n":"complexattrs","t":"complexattrs","d":"semagrams.util","k":"object","x":""},
{"l":"semagrams/util/complexattrs$.html#cxy-0","e":false,"i":"","n":"cxy","t":"cxy: CustomSvgAttr[Complex]","d":"semagrams.util.complexattrs","k":"val","x":""},
{"l":"semagrams/util/complexattrs$.html#pathElts-0","e":false,"i":"","n":"pathElts","t":"pathElts: CustomSvgAttr[Seq[Element]]","d":"semagrams.util.complexattrs","k":"val","x":""},
{"l":"semagrams/util/complexattrs$.html#pointsC-0","e":false,"i":"","n":"pointsC","t":"pointsC: CustomSvgAttr[Seq[Complex]]","d":"semagrams.util.complexattrs","k":"val","x":""},
{"l":"semagrams/util/complexattrs$.html#wh-0","e":false,"i":"","n":"wh","t":"wh: CustomSvgAttr[Complex]","d":"semagrams.util.complexattrs","k":"val","x":""},
{"l":"semagrams/util/complexattrs$.html#xy-0","e":false,"i":"","n":"xy","t":"xy: CustomSvgAttr[Complex]","d":"semagrams.util.complexattrs","k":"val","x":""},
{"l":"semagrams/util/complexattrs$.html#z1-0","e":false,"i":"","n":"z1","t":"z1: CustomSvgAttr[Complex]","d":"semagrams.util.complexattrs","k":"val","x":""},
{"l":"semagrams/util/complexattrs$.html#z2-0","e":false,"i":"","n":"z2","t":"z2: CustomSvgAttr[Complex]","d":"semagrams.util.complexattrs","k":"val","x":""},
{"l":"semagrams/ACSetBalloon.html#","e":false,"i":"","n":"ACSetBalloon","t":"ACSetBalloon(current: Clean) extends PureBalloon[Patch, Clean]","d":"semagrams","k":"class","x":""},
{"l":"semagrams/ACSetBalloon.html#next-fffff53b","e":false,"i":"","n":"next","t":"next(msg: Patch): PureBalloon[Patch, Clean]","d":"semagrams.ACSetBalloon","k":"def","x":""},
{"l":"semagrams/EditorState.html#","e":false,"i":"","n":"EditorState","t":"EditorState(hovered: Option[Part], mousePos: Complex) extends PureBalloon[Event, EditorState]","d":"semagrams","k":"class","x":""},
{"l":"semagrams/EditorState.html#current-0","e":false,"i":"","n":"current","t":"current: EditorState","d":"semagrams.EditorState","k":"def","x":""},
{"l":"semagrams/EditorState.html#next-ca8","e":false,"i":"","n":"next","t":"next(evt: Event): EditorState","d":"semagrams.EditorState","k":"def","x":""},
{"l":"semagrams/EditorState$.html#","e":false,"i":"","n":"EditorState","t":"EditorState","d":"semagrams","k":"object","x":""},
{"l":"semagrams/EditorState$$Event.html#","e":false,"i":"","n":"Event","t":"Event","d":"semagrams.EditorState","k":"enum","x":""},
{"l":"semagrams/EditorState$$Event$$Hover.html#","e":false,"i":"","n":"Hover","t":"Hover(part: Part)","d":"semagrams.EditorState.Event","k":"case","x":""},
{"l":"semagrams/EditorState$$Event$$UnHover.html#","e":false,"i":"","n":"UnHover","t":"UnHover(part: Part)","d":"semagrams.EditorState.Event","k":"case","x":""},
{"l":"semagrams/EditorState$$Event$$MouseMove.html#","e":false,"i":"","n":"MouseMove","t":"MouseMove(pos: Complex)","d":"semagrams.EditorState.Event","k":"case","x":""},
{"l":"semagrams/EditorState$$Event$$Hover.html#","e":false,"i":"","n":"Hover","t":"Hover(part: Part)","d":"semagrams.EditorState.Event","k":"case","x":""},
{"l":"semagrams/EditorState$$Event$$UnHover.html#","e":false,"i":"","n":"UnHover","t":"UnHover(part: Part)","d":"semagrams.EditorState.Event","k":"case","x":""},
{"l":"semagrams/EditorState$$Event$$MouseMove.html#","e":false,"i":"","n":"MouseMove","t":"MouseMove(pos: Complex)","d":"semagrams.EditorState.Event","k":"case","x":""},
{"l":"semagrams/GlobalEvent.html#","e":false,"i":"","n":"GlobalEvent","t":"GlobalEvent","d":"semagrams","k":"enum","x":""},
{"l":"semagrams/GlobalEvent$$KeyDown.html#","e":false,"i":"","n":"KeyDown","t":"KeyDown(key: String)","d":"semagrams.GlobalEvent","k":"case","x":""},
{"l":"semagrams/GlobalEvent$$KeyUp.html#","e":false,"i":"","n":"KeyUp","t":"KeyUp(key: String)","d":"semagrams.GlobalEvent","k":"case","x":""},
{"l":"semagrams/GlobalEvent$$KeyDown.html#","e":false,"i":"","n":"KeyDown","t":"KeyDown(key: String)","d":"semagrams.GlobalEvent","k":"case","x":""},
{"l":"semagrams/GlobalEvent$$KeyUp.html#","e":false,"i":"","n":"KeyUp","t":"KeyUp(key: String)","d":"semagrams.GlobalEvent","k":"case","x":""},
{"l":"semagrams/GlobalState.html#","e":false,"i":"","n":"GlobalState","t":"GlobalState(modifiers: Set[KeyModifier]) extends PureBalloon[GlobalEvent, GlobalState]","d":"semagrams","k":"class","x":""},
{"l":"semagrams/GlobalState.html#current-0","e":false,"i":"","n":"current","t":"current: GlobalState","d":"semagrams.GlobalState","k":"def","x":""},
{"l":"semagrams/GlobalState.html#next-7ac","e":false,"i":"","n":"next","t":"next(evt: GlobalEvent): PureBalloon[GlobalEvent, GlobalState]","d":"semagrams.GlobalState","k":"def","x":""},
{"l":"semagrams/KeyModifier.html#","e":false,"i":"","n":"KeyModifier","t":"KeyModifier","d":"semagrams","k":"enum","x":""},
{"l":"semagrams/KeyModifier.html#Ctrl-0","e":false,"i":"","n":"Ctrl","t":"Ctrl extends KeyModifier","d":"semagrams.KeyModifier","k":"case","x":""},
{"l":"semagrams/KeyModifier.html#Shift-0","e":false,"i":"","n":"Shift","t":"Shift extends KeyModifier","d":"semagrams.KeyModifier","k":"case","x":""},
{"l":"semagrams/KeyModifier.html#Meta-0","e":false,"i":"","n":"Meta","t":"Meta extends KeyModifier","d":"semagrams.KeyModifier","k":"case","x":""},
{"l":"semagrams/KeyModifier.html#Alt-0","e":false,"i":"","n":"Alt","t":"Alt extends KeyModifier","d":"semagrams.KeyModifier","k":"case","x":""},
{"l":"semagrams/KeyModifier$.html#","e":false,"i":"","n":"KeyModifier","t":"KeyModifier","d":"semagrams","k":"object","x":""},
{"l":"semagrams/KeyModifier$.html#all-0","e":false,"i":"","n":"all","t":"all: Set[KeyModifier]","d":"semagrams.KeyModifier","k":"val","x":""},
{"l":"semagrams/KeyModifier$.html#asString-0","e":false,"i":"","n":"asString","t":"asString: Map[KeyModifier, String]","d":"semagrams.KeyModifier","k":"val","x":""},
{"l":"semagrams/KeyModifier$.html#fromString-0","e":false,"i":"","n":"fromString","t":"fromString: Map[String, KeyModifier]","d":"semagrams.KeyModifier","k":"val","x":""},
{"l":"semagrams/LocalEvent.html#","e":false,"i":"","n":"LocalEvent","t":"LocalEvent","d":"semagrams","k":"enum","x":""},
{"l":"semagrams/LocalEvent$$MouseEnter.html#","e":false,"i":"","n":"MouseEnter","t":"MouseEnter(ent: Part)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseLeave.html#","e":false,"i":"","n":"MouseLeave","t":"MouseLeave(ent: Part)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseDown.html#","e":false,"i":"","n":"MouseDown","t":"MouseDown(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseUp.html#","e":false,"i":"","n":"MouseUp","t":"MouseUp(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$Click.html#","e":false,"i":"","n":"Click","t":"Click(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$DoubleClick.html#","e":false,"i":"","n":"DoubleClick","t":"DoubleClick(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseLeaveBox.html#","e":false,"i":"","n":"MouseLeaveBox","t":"MouseLeaveBox(pos: Complex)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseMove.html#","e":false,"i":"","n":"MouseMove","t":"MouseMove(pos: Complex)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$ContextMenu.html#","e":false,"i":"","n":"ContextMenu","t":"ContextMenu(ent: Option[Part])","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseEnter.html#","e":false,"i":"","n":"MouseEnter","t":"MouseEnter(ent: Part)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseLeave.html#","e":false,"i":"","n":"MouseLeave","t":"MouseLeave(ent: Part)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseDown.html#","e":false,"i":"","n":"MouseDown","t":"MouseDown(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseUp.html#","e":false,"i":"","n":"MouseUp","t":"MouseUp(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$Click.html#","e":false,"i":"","n":"Click","t":"Click(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$DoubleClick.html#","e":false,"i":"","n":"DoubleClick","t":"DoubleClick(ent: Option[Part], button: MouseButton)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseLeaveBox.html#","e":false,"i":"","n":"MouseLeaveBox","t":"MouseLeaveBox(pos: Complex)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$MouseMove.html#","e":false,"i":"","n":"MouseMove","t":"MouseMove(pos: Complex)","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/LocalEvent$$ContextMenu.html#","e":false,"i":"","n":"ContextMenu","t":"ContextMenu(ent: Option[Part])","d":"semagrams.LocalEvent","k":"case","x":""},
{"l":"semagrams/MouseButton.html#","e":false,"i":"","n":"MouseButton","t":"MouseButton","d":"semagrams","k":"enum","x":""},
{"l":"semagrams/MouseButton.html#Left-0","e":false,"i":"","n":"Left","t":"Left extends MouseButton","d":"semagrams.MouseButton","k":"case","x":""},
{"l":"semagrams/MouseButton.html#Middle-0","e":false,"i":"","n":"Middle","t":"Middle extends MouseButton","d":"semagrams.MouseButton","k":"case","x":""},
{"l":"semagrams/MouseButton.html#Right-0","e":false,"i":"","n":"Right","t":"Right extends MouseButton","d":"semagrams.MouseButton","k":"case","x":""},
{"l":"semagrams/MouseButton$.html#","e":false,"i":"","n":"MouseButton","t":"MouseButton","d":"semagrams","k":"object","x":""},
{"l":"semagrams/MouseButton$.html#fromJS-eb8","e":false,"i":"","n":"fromJS","t":"fromJS(idx: Int): MouseButton","d":"semagrams.MouseButton","k":"def","x":""},
{"l":"semagrams/Position$.html#","e":false,"i":"","n":"Position","t":"Position extends Property","d":"semagrams","k":"object","x":""},
{"l":"semagrams/Position$.html#id-0","e":false,"i":"","n":"id","t":"id: PropId","d":"semagrams.Position","k":"val","x":""},
{"l":"semagrams/Position$.html#valueType-0","e":false,"i":"","n":"valueType","t":"valueType: C.type","d":"semagrams.Position","k":"val","x":""}];