on:
  pull_request:
  push:
    branches: main

name: Build and Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Mill
        uses: jodersky/setup-mill@master
        with:
          mill-version: '0.11.5'

      - name: Set up NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Core Tests
        run: |
          cd scala
          npm install
          mill acsets.test
          mill balloons.test
          mill core.test

  checkFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Mill
        uses: jodersky/setup-mill@master
        with:
          mill-version: '0.11.5'

      - name: Check formatting
        run: |
          cd scala
          mill acsets.checkFormat
          mill balloons.checkFormat
          mill core.checkFormat
          for app in $(mill resolve apps._)
          do
            mill "$app.checkFormat"
          done

  build-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Mill
        uses: jodersky/setup-mill@master
        with:
          mill-version: '0.11.5'

      - name: Build compiled javascript
        run: |
          cd scala
          for app in $(mill resolve apps._)
          do
            mill $app.compile
          done
