on:
  push:
    branches: main

name: Build and Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Mill
        uses: jodersky/setup-mill@master
        with:
          mill-version: '0.10.5'

      - run: |
          cd scala
          mill core.test

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Mill
        uses: jodersky/setup-mill@master
        with:
          mill-version: '0.10.5'

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build compiled javascript
        run: |
          cd scala
          mill apps.petri.fullLinkJS

      - name: Get shorthash
        id: shorthash
        run: |
          hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "::set-output name=sh::$hash"

      - name: Copy files to bucket
        run: |
          hash=${{ steps.shorthash.outputs.sh }}
          mkdir -p build/$hash/petri
          cp scala/out/apps/petri/fullLinkJS.dest/* build/$hash/petri/
          aws s3 sync build/ s3://semagrams-builds

      - name: Create link to files in commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Find compiled javascript for
            - [Petri app](https://semagrams-builds.s3.amazonaws.com/${{ steps.shorthash.outputs.sh }}/petri/main.js)
