name: Publish to NPM
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: cd javascript
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secretes.NPM_ACCESS_TOKEN }}
