name: Publish to NPM
on: push

jobs:
  publish:
    environment: npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
        working-directory: ./javascript
      - run: npm run build
        working-directory: ./javascript
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          package: ./javascript/package.json
