on:
  push:
    branches: next

name: Build and Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Mill
        uses: jodersky/setup-mill
        with:
          mill-version: '0.10.5'

      - run: |
          cd scala
          mill core.test
          mill apps.petri.compile
