name: Build Website
on:
  push:
    branches:
      - main
jobs:
  build-website:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    # NOTE: uncomment the following lines if you intend to use PyPlot
    # - name: Install python
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: '3.8'
    # - run: pip install matplotlib
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.6
    # NOTE
    # Adjust the `input=""` on the last line to indicate where
    # the source of the package page is (`page/` by default).
    #
    # Adjust also `output=""` on the last line if you want
    # the page to be deployed in a specific folder on gh-pages
    # if you do that, make sure that you adjust the `prepath`
    # variable in `config.md` accordingly! so for instance
    # if you set here `folder="web"` change prepath for
    # `@def prepath = "YourPackage.jl/web"`
    - run: julia -e '
            using Pkg;
            Pkg.add(["NodeJS", "PkgPage", "DataFrames"]);
            using NodeJS;
            run(`$(npm_cmd()) install highlight.js purgecss`);
            import PkgPage;
            PkgPage.optimize(prepath="Semagrams.jl", prerender=false, input="page", output="")'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: page/__site
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
